# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  chromeVersion: '100.0.4896.75'

steps:
  
- task: PowerShell@2
  displayName: '01. Acquire the Chrome version installed on this darned machine'
  inputs:
    targetType: 'inline'
    script: '(Get-Item "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo'

- task: UseDotNet@2
  displayName: '02. Acquire .NET Core sdk 5.0.100'
  inputs:
    packageType: 'sdk'
    version: '5.0.100'
    includePreviewVersions: false

- task: NuGetToolInstaller@1
  displayName: '03. Acquire NuGet 5.8'
  inputs:
    versionSpec: '5.8'
    checkLatest: true

- task: NuGetCommand@2
  displayName: '04. Restore NuGet packages for specified project'
  inputs:
    command: 'restore'
    restoreSolution: '**/*Test/*.csproj'
    feedsToUse: 'select'
    noCache: true

- task: DotNetCoreCLI@2
  displayName: '05. Execute the tests in the test solution.'
  inputs:
    command: 'test'
    projects: '**/*Test/*.csproj'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: '06. Build $(buildConfiguration) version of project'

- task: DotNetCoreCLI@2
  displayName: '07. Build Test project'
  inputs:
    projects: '**/*Test/*.csproj'
    arguments: '--runtime win-x64'
  continueOnError: true

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#   inputs:
#     command: build
#     publishWebProjects: false
#     projects: 'src/TechFabricSln/TechFabricSln.csproj'
#     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)\TechFabricSln'
#     zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: '08. Publish Build artifacts'
  inputs:
    PathtoPublish: 'D:\a\1\'
    ArtifactName: 'TechFabricSln'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  displayName: '09. Publish Test artifacts'
  # displayName: 'dotnet publish test --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'test\TestFabricSln.Test\TestFabricSln.Test.csproj'
    arguments: '-p:PublishChromeDriver=true --runtime win-x64 --output $(Build.ArtifactStagingDirectory)\TestFabricSln.Test'
    modifyOutputPath: true
    zipAfterPublish: false

# - task: PublishBuildArtifacts@1
#   displayName: '10. Publish artifacts'
